# Generated by Django 3.1 on 2021-08-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birthday_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
