# Generated by Django 3.1 on 2021-09-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-id'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
