# Generated by Django 2.2 on 2021-02-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210131_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='телефон'),
        ),
    ]
