# Generated by Django 2.2 on 2021-02-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210206_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='growcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активность'),
        ),
        migrations.AddField(
            model_name='growproducts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активность'),
        ),
    ]
