# Generated by Django 2.2 on 2021-04-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210215_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='growcategory',
            options={'ordering': ['name'], 'verbose_name': 'категория продукта', 'verbose_name_plural': 'категории продукта'},
        ),
        migrations.AlterModelOptions(
            name='growproducts',
            options={'ordering': ['name'], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterField(
            model_name='growcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активность'),
        ),
        migrations.AlterField(
            model_name='growproducts',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активность'),
        ),
    ]
