# Generated by Django 2.2 on 2021-02-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='growuser',
            name='age_user',
            field=models.PositiveIntegerField(null=True, verbose_name='возраст'),
        ),
        migrations.AddField(
            model_name='growuser',
            name='avatar_user',
            field=models.ImageField(blank=True, upload_to='users_avatar'),
        ),
    ]
