# Generated by Django 2.2 on 2021-04-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210206_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='growuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='growuser',
            name='user_activation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
