# Generated by Django 2.2 on 2021-04-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210404_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growuser',
            name='user_activation_date',
        ),
    ]
