# Generated by Django 2.2 on 2021-04-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_growuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='growuserprofile',
            name='about_me',
            field=models.CharField(blank=True, max_length=256, verbose_name='text about'),
        ),
    ]
