# Generated by Django 2.2 on 2021-04-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20210408_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='growuserprofile',
            name='city',
            field=models.CharField(blank=True, max_length=25, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='growuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('W', 'female')], max_length=1, verbose_name='gender'),
        ),
    ]
