# Generated by Django 2.2 on 2021-04-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20210409_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growuserprofile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='growuserprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='growuserprofile',
            name='language_user',
            field=models.CharField(blank=True, max_length=5, verbose_name='ln'),
        ),
        migrations.AddField(
            model_name='growuserprofile',
            name='url_user',
            field=models.CharField(blank=True, max_length=100, verbose_name='url'),
        ),
    ]
