# Generated by Django 2.2 on 2021-04-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20210409_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growuserprofile',
            name='url_user',
            field=models.CharField(blank=True, max_length=150, verbose_name='url'),
        ),
    ]
