# Generated by Django 2.2 on 2021-04-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_auto_20210414_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активность заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('f', 'формируется'), ('s', 'отправлен'), ('p', 'оплачен'), ('c', 'отменен')], db_index=True, default='f', max_length=1, verbose_name='cтатус'),
        ),
    ]
